add_newline = true
palette = 'nord'

format = '''
[┌─$username$hostname─$directory](nord3)
[└─$git_branch$git_state$git_status─$character](nord3)
'''

right_format = '[$time](nord3)'

[character]
success_symbol = '[❯](nord4)'
error_symbol = '[❯](nord4)'

[directory]
format = '\([$path]($style)[$read_only]($read_only_style)\)'
read_only_style = 'nord11'
style = 'nord9'
truncation_length = 7
truncation_symbol = '…/'

[git_branch]
format = '\([$branch$symbol]($style) '
style = 'nord9'
symbol = ' '

[git_state]
style = 'nord9'

[git_status]
format = '([\[$all_status$ahead_behind\]]($style))\)'
style = 'nord9'

[hostname]
format = '[@$hostname]($style)\)'
ssh_only = false
style = 'nord9'

[time]
disabled = false
format = '\([$time]($style)\)'
style = 'nord9'
time_format = '%H:%M %d/%m/%y'

[username]
format = '\([$user]($style)'
show_always = true
style_root = 'nord11 bold'
style_user = 'nord9'

[palettes.nord]
nord0 = "#2e3440"
nord1 = "#3b4252"
nord2 = "#434c5e"
nord3 = "#4c566a"
nord4 = "#d8dee9"
nord5 = "#e5e9f0"
nord6 = "#eceff4"
nord7 = "#8fbcbb"
nord8 = "#88c0d0"
nord9 = "#81a1c1"
nord10 = "#5e81ac"
nord11 = "#bf616a"
nord12 = "#d08770"
nord13 = "#ebcb8b"
nord14 = "#a3be8c"
nord15 = "#b48ead"
