# Set up the prompt

autoload -Uz promptinit
# promptinit
# prompt adam1

setopt histignorealldups sharehistory

# Use emacs keybindings even if our EDITOR is set to vi
bindkey -e

# Keep 1000 lines of history within the shell and save it to ~/.zsh_history:
HISTSIZE=1000
SAVEHIST=1000
HISTFILE=~/.zsh_history

# Use modern completion system
autoload -Uz compinit
compinit

zstyle ':completion:*' auto-description 'specify: %d'
zstyle ':completion:*' completer _expand _complete _correct _approximate
zstyle ':completion:*' format 'Completing %d'
zstyle ':completion:*' group-name ''
zstyle ':completion:*' menu select=2
eval "$(dircolors -b)"
zstyle ':completion:*:default' list-colors ${(s.:.)LS_COLORS}
zstyle ':completion:*' list-colors ''
zstyle ':completion:*' list-prompt %SAt %p: Hit TAB for more, or the character to insert%s
zstyle ':completion:*' matcher-list '' 'm:{a-z}={A-Z}' 'm:{a-zA-Z}={A-Za-z}' 'r:|[._-]=* r:|=* l:|=*'
zstyle ':completion:*' menu select=long
zstyle ':completion:*' select-prompt %SScrolling active: current selection at %p%s
zstyle ':completion:*' use-compctl false
zstyle ':completion:*' verbose true

zstyle ':completion:*:*:kill:*:processes' list-colors '=(#b) #([0-9]#)*=0=01;31'
zstyle ':completion:*:kill:*' command 'ps -u $USER -o pid,%cpu,tty,cputime,cmd'

#Alias
## ls
alias ls='ls --color=auto'

## xrandr
alias moHdmiPLeft='xrandr --output HDMI-1 --auto --primary --left-of eDP-1 --output eDP-1 --auto'
alias moHdmiPRight='xrandr --output HDMI-1 --auto --primary --right-of eDP-1 --output eDP-1 --auto'
alias moHdmiPClone='xrandr --output HDMI-1 --auto --primary --same-as eDP-1 --output eDP-1 --auto'
alias moHdmiOnly='xrandr --output HDMI-1 --auto --primary --output eDP-1 --off'

alias moEdpPLeft='xrandr --output eDP-1 --auto --primary --left-of HDM1 --output HDM1 --auto'
alias moEdpPRight='xrandr --output eDP-1 --auto --primary --right-of HDMI-1 --output HDMI-1 --auto'
alias moEdpPClone='xrandr --output eDP-1 --auto --primary --same-as HDMI-1 --output HDMI-1 --auto'
alias moEdpOnly='xrandr --output eDP-1 --auto --primary --output HDM1 --off'

# Prompt configuration
setopt PROMPT_SUBST
prompt() {

    local TERMWIDTH=$(($COLUMNS + 2))
    local RIGHT='(%D{%a %b %d})'
    local LEFT='┌─[%B%n@%m%b] (%B%F{green}%~%f%b)'
    local MAIN='└─(%D{%I:%M})─(%#)─ '

    printf "%*s\r%s\n%s" "$(($TERMWIDTH))" "$RIGHT" "$LEFT" "$MAIN"
}
PROMPT='$(prompt)'
